"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "SchnozzleCat"
email = "linus@schnozzlecat.xyz"

[ui]
paginate = "never"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[signing]
behavior = "own"
backend = "gpg"
