# TODO:
# - combine binary and source tests
# - filter builtInputs by builtin_ flags
{
  callPackage,
  lib,
  nix-update-script,
  fetchzip,
  pkgs,
}: let
  mkGodotPackages = versionPrefix: sourceOverrides: let
    # Pin from the version directory, with user-provided source overrides
    # (rev/hash) taking precedence.
    attrs = import (./. + "/${versionPrefix}/default.nix") // sourceOverrides;
    updateScript = [
      ./update.sh
      versionPrefix
      (builtins.unsafeGetAttrPos "version" attrs).file
    ];

    # Tracy profiler source, needed by builds with `withTracy = true`. The
    # hash is of the tag tarball itself (builtins.fetchTarball), because a
    # fetchFromGitHub tree-hash cannot be pre-computed in this environment.
    # The version must match the one used by the Tracy profiler GUI
    # ("server") when inspecting recorded traces.
    # https://docs.godotengine.org/en/stable/engine_details/development/profiling/tracy.html
    tracy = builtins.fetchTarball {
      url = "https://github.com/wolfpld/tracy/archive/refs/tags/v0.13.1.tar.gz";
      sha256 = "sha256-D4aQ5kSfWH9qEUaithR0W/E5pN5on0n9YoBHeMggMSE=";
    };
  in
    lib.recurseIntoAttrs rec {
      godot = callPackage ./common.nix {
        inherit updateScript tracy;
        inherit
          (attrs)
          version
          rev
          hash
          ;
        inherit
          (attrs.default)
          exportTemplatesHash
          ;
      };

      godot-mono = godot.override {
        withMono = true;
        inherit
          (attrs.mono)
          exportTemplatesHash
          nugetDeps
          ;
      };

      # Builds with the built-in Tracy profiler.
      # https://docs.godotengine.org/en/stable/engine_details/development/profiling/tracy.html
      godot-tracy = godot.override {withTracy = true;};
      godot-mono-tracy = godot-mono.override {withTracy = true;};

      export-template = godot.export-template;
      export-template-mono = godot-mono.export-template;

      export-templates-bin = godot.export-templates-bin;
      export-templates-mono-bin = godot-mono.export-templates-bin;

      # Windows cross-compilation from Linux (MinGW-w64), see:
      # https://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html
      # and the official build scripts:
      # https://github.com/godotengine/godot-build-scripts/blob/master/build-windows/build.sh
      #
      # These need `steamworks_sdk_164.zip` in the store (same as Linux).

      # Mono glue: C# API bindings generated by running the Linux mono editor
      # of the same source rev. Required because glue generation is a runtime
      # action of the built editor binary, which cannot run when
      # cross-compiling for windows (no wine in the build sandbox).
      mono-glue = callPackage ./mono-glue.nix {godot-editor = godot-mono;};

      # The linuxbsd build uses system libraries via pkg-config; the windows
      # build uses all-builtin libraries instead, so these are passed as null
      # to avoid evaluating (and potentially failing to) cross-compile them.
      linuxOnlyDeps = {
        alsa-lib = null;
        autoPatchelfHook = null;
        dbus = null;
        embree = null;
        enet = null;
        # NOTE: fetchFromGitHub must NOT be nulled here -- it's used for the
        # source fetch in common.nix and works fine in the cross package set.
        fetchpatch = null;
        fontconfig = null;
        freetype = null;
        glib = null;
        glslang = null;
        graphite2 = null;
        harfbuzz = null;
        icu = null;
        installShellFiles = null;
        libdecor = null;
        libGL = null;
        libjpeg_turbo = null;
        libpulseaudio = null;
        libtheora = null;
        libwebp = null;
        libX11 = null;
        libXcursor = null;
        libXext = null;
        libXfixes = null;
        libXi = null;
        libXinerama = null;
        libxkbcommon = null;
        libXrandr = null;
        libXrender = null;
        makeWrapper = null;
        mbedtls = null;
        miniupnpc = null;
        openxr-loader = null;
        pcre2 = null;
        pkg-config = null;
        recastnavigation = null;
        sdl3 = null;
        speechd-minimal = null;
        udev = null;
        vulkan-loader = null;
        wayland = null;
        wayland-scanner = null;
        wslay = null;
        zstd = null;
      };

      windowsCommonArgs =
        {
          inherit updateScript;
          inherit
            (attrs)
            version
            rev
            hash
            ;
          inherit
            (attrs.default)
            exportTemplatesHash
            ;
          withPlatform = "windows";
          # Tracy profiler source for `withTracy = true` builds (host-fetched;
          # only used as a source input).
          inherit tracy;
          # Prebuilt Mesa/NIR static libraries for the D3D12 driver.
          mesaNir = pkgs.callPackage ./d3d12-deps.nix {};
          # The .NET SDK and the requireFile machinery are host (Linux)
          # tools; take them from the native package set rather than the
          # mingw cross set.
          dotnetCorePackages = pkgs.dotnetCorePackages;
          requireFile = pkgs.requireFile;
        }
        // linuxOnlyDeps;

      # Classical (non-mono) Windows editor; mostly useful for testing the
      # cross-compilation pipeline without the .NET overhead.
      godot-windows = pkgs.pkgsCross.mingwW64.callPackage ./common.nix (windowsCommonArgs // {withMono = false;});

      # Mono-enabled (C#) Windows editor + export templates.
      godot-mono-windows = pkgs.pkgsCross.mingwW64.callPackage ./common.nix (
        windowsCommonArgs
        // {
          withMono = true;
          inherit (attrs.mono) nugetDeps;
          inherit mono-glue;
        }
      );

      godot-mono-windows-template = godot-mono-windows.export-template;
      godot-mono-windows-template-debug = godot-mono-windows.export-template-debug;
    };
in {
  # Version-parameterized interface so modules can forward their own version
  # and source overrides: mkGodotPackages "4.7" {} resolves ./4.7/default.nix.
  inherit mkGodotPackages;

  godotPackages_4_7 = mkGodotPackages "4.7" {};
}
